name: TaskManager

services:
  api:
    build:
      context: ../..
      dockerfile: Docker/API/Dockerfile
    container_name: TaskManager_API
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=TaskManagerDb;
        User Id=sa;
        Password="${DB_PASSWORD}";
        TrustServerCertificate=True;
      Redis__ConnectionString: "redis:6379"
      Jwt__Key: "${JWT_KEY}"
      Jwt__Issuer: "TaskManager.API"
      Jwt__Audience: "TaskManager.Client"
      Jwt__ExpirationInMinutes: "60"
      Ollama__BaseUrl: "http://ollama:11434/"
      Cors__AllowedOrigins__0: "http://localhost:5173"
    networks:
      - databases
    restart: on-failure

networks:
  databases:
    external: true
    name: taskmanager_databases